# Generated by Django 4.0.6 on 2022-07-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_movies_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('actors', models.CharField(max_length=500)),
                ('genre', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
