# Generated by Django 4.0.6 on 2022-07-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_ratings_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rate',
            field=models.CharField(choices=[('1', 'Loved it'), ('2', 'it is ok'), ('3', 'Fell asleep while watching')], default='1', max_length=10),
        ),
    ]
