# Generated by Django 4.0.6 on 2022-07-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='movie',
            new_name='movies',
        ),
    ]
