# Generated by Django 4.0.6 on 2022-07-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_movie_photo_movies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='movies',
            new_name='movie',
        ),
    ]
